=== jessicahydesfather/Projet-L1/XML/definition.dtd
<!ELEMENT carte (nom,categories*,contact)>
	<!ELEMENT nom (#PCDATA)>
	<!ELEMENT categories (cat*, plats, illu, indispo?)>
		<!ELEMENT cat (plats*, illu)>
			<!ELEMENT plats (#PCDATA)>
			<!ATTLIST plats type CDATA #IMPLIED>
			<!ELEMENT illu (#PCDATA) >
		<!ELEMENT indispo (#PCDATA)>
	<!ELEMENT contact (logo?, adresse)>
		<!ELEMENT logo (#PCDATA)>
		<!ELEMENT adresse (#PCDATA)>

=== jessicahydesfather/Projet-L1/XML/exemple.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE exemple SYSTEM "definition.dtd">

<carte>
	<nom></nom>
	<categorie>
		<cat></cat>
		<plats></plats>
		<illu></illu>
	</categorie>
	<categorie>
		<cat></cat>
		<plats></plats>
		<illu></illu>
		<indispo></indispo>
		</categorie>
	<categorie>
		<cat></cat>
		<plats></plats>
		<illu></illu>
	</categorie>
	<contact>
		<logo></logo>
		<adresse></adresse>
	</contact>
</carte>
